username = "admin"
password = "admin"
host  = "192.168.31.100"
port = "5672"
virtual_host = "/"
exchange_name = "drink-topic-exchange"
exchange_type = "topic"

binding_key_kafei = "caffeine.#"
binding_key_naicha = "nocaffeine.hot.sweet"
binding_key_guozhi = "nocaffeine.*.sweet"

queue_name_coffee = "coffee"
queue_name_milktea = "milktea"
queue_name_juice = "juice"